<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitiesSeeder extends Seeder
{
    public function run(): void
    {
        $cities = $this->getAllCities();
        
        foreach ($cities as $city) {
            DB::table('cities')->updateOrInsert(
                ['id' => $city['id']],
                $city
            );
        }
    }

    private function getAllCities(): array
    {
        return [
            // Europa
            ['id' => 1, 'name_translations' => json_encode(['en' => 'London', 'de' => 'London']), 'country_id' => 17, 'region_id' => null, 'population' => 9648110, 'lat' => 51.5074, 'lng' => -0.1278, 'is_capital' => true, 'created_at' => now(), 'updated_at' => now()], // GB - Capital
            ['id' => 2, 'name_translations' => json_encode(['en' => 'Paris', 'de' => 'Paris']), 'country_id' => 16, 'region_id' => null, 'population' => 2161000, 'lat' => 48.8566, 'lng' => 2.3522, 'is_capital' => true, 'created_at' => now(), 'updated_at' => now()], // FR - Capital
            ['id' => 3, 'name_translations' => json_encode(['en' => 'Frankfurt am Main', 'de' => 'Frankfurt am Main']), 'country_id' => 12, 'region_id' => null, 'population' => 753056, 'lat' => 50.1109, 'lng' => 8.6821, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // DE
            ['id' => 4, 'name_translations' => json_encode(['en' => 'Amsterdam', 'de' => 'Amsterdam']), 'country_id' => 33, 'region_id' => null, 'population' => 872757, 'lat' => 52.3702, 'lng' => 4.8952, 'is_capital' => true, 'created_at' => now(), 'updated_at' => now()], // NL - Capital
            ['id' => 5, 'name_translations' => json_encode(['en' => 'Madrid', 'de' => 'Madrid']), 'country_id' => 1, 'region_id' => null, 'population' => 3223334, 'lat' => 40.4168, 'lng' => -3.7038, 'is_capital' => true, 'created_at' => now(), 'updated_at' => now()], // ES - Capital
            ['id' => 6, 'name_translations' => json_encode(['en' => 'Rome', 'de' => 'Rom']), 'country_id' => 23, 'region_id' => null, 'population' => 2873494, 'lat' => 41.9028, 'lng' => 12.4964, 'is_capital' => true, 'created_at' => now(), 'updated_at' => now()], // IT - Capital
            ['id' => 7, 'name_translations' => json_encode(['en' => 'Zurich', 'de' => 'Zürich']), 'country_id' => 9, 'region_id' => null, 'population' => 421878, 'lat' => 47.3769, 'lng' => 8.5417, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // CH
            ['id' => 8, 'name_translations' => json_encode(['en' => 'Vienna', 'de' => 'Wien']), 'country_id' => 4, 'region_id' => null, 'population' => 1911191, 'lat' => 48.2082, 'lng' => 16.3738, 'is_capital' => true, 'created_at' => now(), 'updated_at' => now()], // AT - Capital
            ['id' => 9, 'name_translations' => json_encode(['en' => 'Brussels', 'de' => 'Brüssel']), 'country_id' => 6, 'region_id' => null, 'population' => 1211035, 'lat' => 50.8503, 'lng' => 4.3517, 'is_capital' => true, 'created_at' => now(), 'updated_at' => now()], // BE - Capital
            ['id' => 10, 'name_translations' => json_encode(['en' => 'Copenhagen', 'de' => 'Kopenhagen']), 'country_id' => 13, 'region_id' => null, 'population' => 660193, 'lat' => 55.6761, 'lng' => 12.5683, 'is_capital' => true, 'created_at' => now(), 'updated_at' => now()], // DK - Capital
            ['id' => 11, 'name_translations' => json_encode(['en' => 'Stockholm', 'de' => 'Stockholm']), 'country_id' => 40, 'region_id' => null, 'population' => 975551, 'lat' => 59.3293, 'lng' => 18.0686, 'is_capital' => true, 'created_at' => now(), 'updated_at' => now()], // SE - Capital
            ['id' => 12, 'name_translations' => json_encode(['en' => 'Oslo', 'de' => 'Oslo']), 'country_id' => 34, 'region_id' => null, 'population' => 697010, 'lat' => 59.9139, 'lng' => 10.7522, 'is_capital' => true, 'created_at' => now(), 'updated_at' => now()], // NO - Capital
            ['id' => 13, 'name_translations' => json_encode(['en' => 'Helsinki', 'de' => 'Helsinki']), 'country_id' => 15, 'region_id' => null, 'population' => 658457, 'lat' => 60.1699, 'lng' => 24.9384, 'is_capital' => true, 'created_at' => now(), 'updated_at' => now()], // FI - Capital
            ['id' => 14, 'name_translations' => json_encode(['en' => 'Dublin', 'de' => 'Dublin']), 'country_id' => 21, 'region_id' => null, 'population' => 554554, 'lat' => 53.3498, 'lng' => -6.2603, 'is_capital' => true, 'created_at' => now(), 'updated_at' => now()], // IE - Capital
            ['id' => 15, 'name_translations' => json_encode(['en' => 'Athens', 'de' => 'Athen']), 'country_id' => 18, 'region_id' => null, 'population' => 664046, 'lat' => 37.9755, 'lng' => 23.7348, 'is_capital' => true, 'created_at' => now(), 'updated_at' => now()], // GR - Capital
            ['id' => 16, 'name_translations' => json_encode(['en' => 'Lisbon', 'de' => 'Lissabon']), 'country_id' => 36, 'region_id' => null, 'population' => 504718, 'lat' => 38.7223, 'lng' => -9.1393, 'is_capital' => true, 'created_at' => now(), 'updated_at' => now()], // PT - Capital
            ['id' => 17, 'name_translations' => json_encode(['en' => 'Prague', 'de' => 'Prag']), 'country_id' => 11, 'region_id' => null, 'population' => 1309000, 'lat' => 50.0755, 'lng' => 14.4378, 'is_capital' => true, 'created_at' => now(), 'updated_at' => now()], // CZ - Capital
            ['id' => 18, 'name_translations' => json_encode(['en' => 'Warsaw', 'de' => 'Warschau']), 'country_id' => 35, 'region_id' => null, 'population' => 1790658, 'lat' => 52.2297, 'lng' => 21.0122, 'is_capital' => true, 'created_at' => now(), 'updated_at' => now()], // PL - Capital
            ['id' => 19, 'name_translations' => json_encode(['en' => 'Budapest', 'de' => 'Budapest']), 'country_id' => 20, 'region_id' => null, 'population' => 1752286, 'lat' => 47.4979, 'lng' => 19.0402, 'is_capital' => true, 'created_at' => now(), 'updated_at' => now()], // HU - Capital
            ['id' => 20, 'name_translations' => json_encode(['en' => 'Bucharest', 'de' => 'Bukarest']), 'country_id' => 37, 'region_id' => null, 'population' => 1883425, 'lat' => 44.4268, 'lng' => 26.1025, 'is_capital' => true, 'created_at' => now(), 'updated_at' => now()], // RO - Capital
            ['id' => 21, 'name_translations' => json_encode(['en' => 'Istanbul', 'de' => 'Istanbul']), 'country_id' => 87, 'region_id' => null, 'population' => 15519267, 'lat' => 41.0082, 'lng' => 28.9784, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // TR
            ['id' => 22, 'name_translations' => json_encode(['en' => 'Moscow', 'de' => 'Moskau']), 'country_id' => 39, 'region_id' => null, 'population' => 12506468, 'lat' => 55.7558, 'lng' => 37.6176, 'is_capital' => true, 'created_at' => now(), 'updated_at' => now()], // RU - Capital

            // Asien
            ['id' => 23, 'name_translations' => json_encode(['en' => 'Tokyo', 'de' => 'Tokio']), 'country_id' => 61, 'region_id' => null, 'population' => 13960000, 'lat' => 35.6762, 'lng' => 139.6503, 'is_capital' => true, 'created_at' => now(), 'updated_at' => now()], // Japan - Capital
            ['id' => 24, 'name_translations' => json_encode(['en' => 'Beijing', 'de' => 'Peking']), 'country_id' => 53, 'region_id' => null, 'population' => 21542000, 'lat' => 39.9042, 'lng' => 116.4074, 'is_capital' => true, 'created_at' => now(), 'updated_at' => now()], // China - Capital
            ['id' => 25, 'name_translations' => json_encode(['en' => 'Shanghai', 'de' => 'Shanghai']), 'country_id' => 53, 'region_id' => null, 'population' => 27058000, 'lat' => 31.2304, 'lng' => 121.4737, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // China
            ['id' => 26, 'name_translations' => json_encode(['en' => 'Delhi', 'de' => 'Delhi']), 'country_id' => 57, 'region_id' => null, 'population' => 32226000, 'lat' => 28.7041, 'lng' => 77.1025, 'is_capital' => true, 'created_at' => now(), 'updated_at' => now()], // India - Capital
            ['id' => 27, 'name_translations' => json_encode(['en' => 'Mumbai', 'de' => 'Mumbai']), 'country_id' => 57, 'region_id' => null, 'population' => 20411000, 'lat' => 19.0760, 'lng' => 72.8777, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // India
            ['id' => 28, 'name_translations' => json_encode(['en' => 'Bangkok', 'de' => 'Bangkok']), 'country_id' => 83, 'region_id' => null, 'population' => 10539000, 'lat' => 13.7563, 'lng' => 100.5018, 'is_capital' => true, 'created_at' => now(), 'updated_at' => now()], // Thailand - Capital
            ['id' => 29, 'name_translations' => json_encode(['en' => 'Singapore', 'de' => 'Singapur']), 'country_id' => 81, 'region_id' => null, 'population' => 5850000, 'lat' => 1.3521, 'lng' => 103.8198, 'is_capital' => true, 'created_at' => now(), 'updated_at' => now()], // Singapore - Capital
            ['id' => 30, 'name_translations' => json_encode(['en' => 'Hong Kong', 'de' => 'Hongkong']), 'country_id' => 53, 'region_id' => null, 'population' => 7482500, 'lat' => 22.3193, 'lng' => 114.1694, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // China
            ['id' => 31, 'name_translations' => json_encode(['en' => 'Seoul', 'de' => 'Seoul']), 'country_id' => 64, 'region_id' => null, 'population' => 9776000, 'lat' => 37.5665, 'lng' => 126.9780, 'is_capital' => true, 'created_at' => now(), 'updated_at' => now()], // South Korea - Capital
            ['id' => 32, 'name_translations' => json_encode(['en' => 'Taipei', 'de' => 'Taipeh']), 'country_id' => 88, 'region_id' => null, 'population' => 2646204, 'lat' => 25.0330, 'lng' => 121.5654, 'is_capital' => true, 'created_at' => now(), 'updated_at' => now()], // Taiwan - Capital
            ['id' => 33, 'name_translations' => json_encode(['en' => 'Manila', 'de' => 'Manila']), 'country_id' => 76, 'region_id' => null, 'population' => 13484462, 'lat' => 14.5995, 'lng' => 120.9842, 'is_capital' => true, 'created_at' => now(), 'updated_at' => now()], // Philippines - Capital
            ['id' => 34, 'name_translations' => json_encode(['en' => 'Jakarta', 'de' => 'Jakarta']), 'country_id' => 55, 'region_id' => null, 'population' => 10770487, 'lat' => -6.2088, 'lng' => 106.8456, 'is_capital' => true, 'created_at' => now(), 'updated_at' => now()], // Indonesia - Capital
            ['id' => 35, 'name_translations' => json_encode(['en' => 'Kuala Lumpur', 'de' => 'Kuala Lumpur']), 'country_id' => 73, 'region_id' => null, 'population' => 1768000, 'lat' => 3.1390, 'lng' => 101.6869, 'is_capital' => true, 'created_at' => now(), 'updated_at' => now()], // Malaysia - Capital
            ['id' => 36, 'name_translations' => json_encode(['en' => 'Ho Chi Minh City', 'de' => 'Ho-Chi-Minh-Stadt']), 'country_id' => 90, 'region_id' => null, 'population' => 9077158, 'lat' => 10.8231, 'lng' => 106.6297, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // Vietnam
            ['id' => 37, 'name_translations' => json_encode(['en' => 'Doha', 'de' => 'Doha']), 'country_id' => 79, 'region_id' => null, 'population' => 2382000, 'lat' => 25.2854, 'lng' => 51.5310, 'is_capital' => true, 'created_at' => now(), 'updated_at' => now()], // Qatar - Capital
            // Dubai removed - UAE not in countries list
            ['id' => 39, 'name_translations' => json_encode(['en' => 'Tel Aviv', 'de' => 'Tel Aviv']), 'country_id' => 56, 'region_id' => null, 'population' => 460613, 'lat' => 32.0853, 'lng' => 34.7818, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // Israel
            ['id' => 40, 'name_translations' => json_encode(['en' => 'Riyadh', 'de' => 'Riad']), 'country_id' => 80, 'region_id' => null, 'population' => 7676654, 'lat' => 24.7136, 'lng' => 46.6753, 'is_capital' => true, 'created_at' => now(), 'updated_at' => now()], // Saudi Arabia - Capital

            // Afrika
            ['id' => 41, 'name_translations' => json_encode(['en' => 'Cairo', 'de' => 'Kairo']), 'country_id' => 93, 'region_id' => null, 'population' => 20901000, 'lat' => 30.0444, 'lng' => 31.2357, 'is_capital' => true, 'created_at' => now(), 'updated_at' => now()], // Egypt - Capital
            ['id' => 42, 'name_translations' => json_encode(['en' => 'Johannesburg', 'de' => 'Johannesburg']), 'country_id' => 96, 'region_id' => null, 'population' => 4434827, 'lat' => -26.2041, 'lng' => 28.0473, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // South Africa
            ['id' => 43, 'name_translations' => json_encode(['en' => 'Cape Town', 'de' => 'Kapstadt']), 'country_id' => 96, 'region_id' => null, 'population' => 4618000, 'lat' => -33.9249, 'lng' => 18.4241, 'is_capital' => true, 'created_at' => now(), 'updated_at' => now()], // South Africa - Capital
            ['id' => 44, 'name_translations' => json_encode(['en' => 'Lagos', 'de' => 'Lagos']), 'country_id' => 95, 'region_id' => null, 'population' => 14862000, 'lat' => 6.5244, 'lng' => 3.3792, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // Nigeria
            ['id' => 45, 'name_translations' => json_encode(['en' => 'Nairobi', 'de' => 'Nairobi']), 'country_id' => 97, 'region_id' => null, 'population' => 4397073, 'lat' => -1.2921, 'lng' => 36.8219, 'is_capital' => true, 'created_at' => now(), 'updated_at' => now()], // Kenya - Capital
            ['id' => 46, 'name_translations' => json_encode(['en' => 'Casablanca', 'de' => 'Casablanca']), 'country_id' => 94, 'region_id' => null, 'population' => 3359818, 'lat' => 33.5731, 'lng' => -7.5898, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // Morocco
            ['id' => 47, 'name_translations' => json_encode(['en' => 'Addis Ababa', 'de' => 'Addis Abeba']), 'country_id' => 99, 'region_id' => null, 'population' => 3040000, 'lat' => 9.1450, 'lng' => 38.7451, 'is_capital' => true, 'created_at' => now(), 'updated_at' => now()], // Ethiopia - Capital

            // Nordamerika
            ['id' => 48, 'name_translations' => json_encode(['en' => 'New York', 'de' => 'New York']), 'country_id' => 101, 'region_id' => null, 'population' => 8336817, 'lat' => 40.7128, 'lng' => -74.0060, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // USA
            ['id' => 49, 'name_translations' => json_encode(['en' => 'Los Angeles', 'de' => 'Los Angeles']), 'country_id' => 101, 'region_id' => null, 'population' => 3979576, 'lat' => 34.0522, 'lng' => -118.2437, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // USA
            ['id' => 50, 'name_translations' => json_encode(['en' => 'Chicago', 'de' => 'Chicago']), 'country_id' => 101, 'region_id' => null, 'population' => 2693976, 'lat' => 41.8781, 'lng' => -87.6298, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // USA
            ['id' => 51, 'name_translations' => json_encode(['en' => 'Miami', 'de' => 'Miami']), 'country_id' => 101, 'region_id' => null, 'population' => 467963, 'lat' => 25.7617, 'lng' => -80.1918, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // USA
            ['id' => 52, 'name_translations' => json_encode(['en' => 'San Francisco', 'de' => 'San Francisco']), 'country_id' => 101, 'region_id' => null, 'population' => 881549, 'lat' => 37.7749, 'lng' => -122.4194, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // USA
            ['id' => 53, 'name_translations' => json_encode(['en' => 'Toronto', 'de' => 'Toronto']), 'country_id' => 100, 'region_id' => null, 'population' => 2794356, 'lat' => 43.6532, 'lng' => -79.3832, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // Canada
            ['id' => 54, 'name_translations' => json_encode(['en' => 'Vancouver', 'de' => 'Vancouver']), 'country_id' => 100, 'region_id' => null, 'population' => 662248, 'lat' => 49.2827, 'lng' => -123.1207, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // Canada
            ['id' => 55, 'name_translations' => json_encode(['en' => 'Montreal', 'de' => 'Montreal']), 'country_id' => 100, 'region_id' => null, 'population' => 1704694, 'lat' => 45.5017, 'lng' => -73.5673, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // Canada
            ['id' => 56, 'name_translations' => json_encode(['en' => 'Mexico City', 'de' => 'Mexiko-Stadt']), 'country_id' => 102, 'region_id' => null, 'population' => 9209944, 'lat' => 19.4326, 'lng' => -99.1332, 'is_capital' => true, 'created_at' => now(), 'updated_at' => now()], // Mexico - Capital

            // Südamerika
            ['id' => 57, 'name_translations' => json_encode(['en' => 'São Paulo', 'de' => 'São Paulo']), 'country_id' => 106, 'region_id' => null, 'population' => 12325232, 'lat' => -23.5558, 'lng' => -46.6396, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // Brazil
            ['id' => 58, 'name_translations' => json_encode(['en' => 'Rio de Janeiro', 'de' => 'Rio de Janeiro']), 'country_id' => 106, 'region_id' => null, 'population' => 6747815, 'lat' => -22.9068, 'lng' => -43.1729, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // Brazil
            ['id' => 59, 'name_translations' => json_encode(['en' => 'Buenos Aires', 'de' => 'Buenos Aires']), 'country_id' => 105, 'region_id' => null, 'population' => 2890151, 'lat' => -34.6118, 'lng' => -58.3960, 'is_capital' => true, 'created_at' => now(), 'updated_at' => now()], // Argentina - Capital
            ['id' => 60, 'name_translations' => json_encode(['en' => 'Lima', 'de' => 'Lima']), 'country_id' => 109, 'region_id' => null, 'population' => 10092000, 'lat' => -12.0464, 'lng' => -77.0428, 'is_capital' => true, 'created_at' => now(), 'updated_at' => now()], // Peru - Capital
            ['id' => 61, 'name_translations' => json_encode(['en' => 'Santiago', 'de' => 'Santiago']), 'country_id' => 107, 'region_id' => null, 'population' => 6257516, 'lat' => -33.4489, 'lng' => -70.6693, 'is_capital' => true, 'created_at' => now(), 'updated_at' => now()], // Chile - Capital
            ['id' => 62, 'name_translations' => json_encode(['en' => 'Bogotá', 'de' => 'Bogotá']), 'country_id' => 108, 'region_id' => null, 'population' => 7412566, 'lat' => 4.7110, 'lng' => -74.0721, 'is_capital' => true, 'created_at' => now(), 'updated_at' => now()], // Colombia - Capital

            // Australien/Ozeanien
            ['id' => 63, 'name_translations' => json_encode(['en' => 'Sydney', 'de' => 'Sydney']), 'country_id' => 112, 'region_id' => null, 'population' => 5312163, 'lat' => -33.8688, 'lng' => 151.2093, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // Australia
            ['id' => 64, 'name_translations' => json_encode(['en' => 'Melbourne', 'de' => 'Melbourne']), 'country_id' => 112, 'region_id' => null, 'population' => 5078193, 'lat' => -37.8136, 'lng' => 144.9631, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // Australia
            ['id' => 65, 'name_translations' => json_encode(['en' => 'Brisbane', 'de' => 'Brisbane']), 'country_id' => 112, 'region_id' => null, 'population' => 2560720, 'lat' => -27.4698, 'lng' => 153.0251, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // Australia
            ['id' => 66, 'name_translations' => json_encode(['en' => 'Perth', 'de' => 'Perth']), 'country_id' => 112, 'region_id' => null, 'population' => 2059484, 'lat' => -31.9505, 'lng' => 115.8605, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // Australia
            ['id' => 67, 'name_translations' => json_encode(['en' => 'Auckland', 'de' => 'Auckland']), 'country_id' => 113, 'region_id' => null, 'population' => 1695200, 'lat' => -36.8485, 'lng' => 174.7633, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // New Zealand

            // Westasien/Mittlerer Osten (West Asia/Middle East)
            ['id' => 1101, 'name_translations' => json_encode(['en' => 'Istanbul', 'de' => 'Istanbul']), 'country_id' => 114, 'region_id' => null, 'population' => 15519267, 'lat' => 41.00824000, 'lng' => 28.97836000, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // Turkey
            ['id' => 1102, 'name_translations' => json_encode(['en' => 'Ankara', 'de' => 'Ankara']), 'country_id' => 114, 'region_id' => null, 'population' => 5663322, 'lat' => 39.92077000, 'lng' => 32.85411000, 'is_capital' => true, 'created_at' => now(), 'updated_at' => now()], // Turkey - Capital
            ['id' => 1103, 'name_translations' => json_encode(['en' => 'Izmir', 'de' => 'Izmir']), 'country_id' => 114, 'region_id' => null, 'population' => 4394694, 'lat' => 38.41885000, 'lng' => 27.12872000, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // Turkey
            ['id' => 1104, 'name_translations' => json_encode(['en' => 'Tehran', 'de' => 'Teheran']), 'country_id' => 86, 'region_id' => null, 'population' => 9259009, 'lat' => 35.69439000, 'lng' => 51.42151000, 'is_capital' => true, 'created_at' => now(), 'updated_at' => now()], // Iran - Capital
            ['id' => 1105, 'name_translations' => json_encode(['en' => 'Isfahan', 'de' => 'Isfahan']), 'country_id' => 86, 'region_id' => null, 'population' => 1961260, 'lat' => 32.65722000, 'lng' => 51.67761000, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // Iran
            ['id' => 1106, 'name_translations' => json_encode(['en' => 'Baghdad', 'de' => 'Bagdad']), 'country_id' => 85, 'region_id' => null, 'population' => 7711305, 'lat' => 33.31240000, 'lng' => 44.36120000, 'is_capital' => true, 'created_at' => now(), 'updated_at' => now()], // Iraq - Capital
            ['id' => 1107, 'name_translations' => json_encode(['en' => 'Damascus', 'de' => 'Damaskus']), 'country_id' => 109, 'region_id' => null, 'population' => 2320000, 'lat' => 33.51302000, 'lng' => 36.27610000, 'is_capital' => true, 'created_at' => now(), 'updated_at' => now()], // Syria - Capital
            ['id' => 1108, 'name_translations' => json_encode(['en' => 'Beirut', 'de' => 'Beirut']), 'country_id' => 95, 'region_id' => null, 'population' => 361366, 'lat' => 33.88733000, 'lng' => 35.51308000, 'is_capital' => true, 'created_at' => now(), 'updated_at' => now()], // Lebanon - Capital
            ['id' => 1109, 'name_translations' => json_encode(['en' => 'Amman', 'de' => 'Amman']), 'country_id' => 87, 'region_id' => null, 'population' => 1275857, 'lat' => 31.95522000, 'lng' => 35.94503000, 'is_capital' => true, 'created_at' => now(), 'updated_at' => now()], // Jordan - Capital
            ['id' => 1110, 'name_translations' => json_encode(['en' => 'Jerusalem', 'de' => 'Jerusalem']), 'country_id' => 83, 'region_id' => null, 'population' => 936425, 'lat' => 31.76904000, 'lng' => 35.21633000, 'is_capital' => true, 'created_at' => now(), 'updated_at' => now()], // Israel - Capital
            ['id' => 1111, 'name_translations' => json_encode(['en' => 'Riyadh', 'de' => 'Riad']), 'country_id' => 107, 'region_id' => null, 'population' => 7676654, 'lat' => 24.71360000, 'lng' => 46.67530000, 'is_capital' => true, 'created_at' => now(), 'updated_at' => now()], // Saudi Arabia - Capital
            ['id' => 1112, 'name_translations' => json_encode(['en' => 'Doha', 'de' => 'Doha']), 'country_id' => 106, 'region_id' => null, 'population' => 2382000, 'lat' => 25.28548000, 'lng' => 51.53096000, 'is_capital' => true, 'created_at' => now(), 'updated_at' => now()], // Qatar - Capital
            ['id' => 1113, 'name_translations' => json_encode(['en' => 'Kuwait City', 'de' => 'Kuwait-Stadt']), 'country_id' => 92, 'region_id' => null, 'population' => 2989000, 'lat' => 29.31166000, 'lng' => 47.48178000, 'is_capital' => true, 'created_at' => now(), 'updated_at' => now()], // Kuwait - Capital
            ['id' => 1114, 'name_translations' => json_encode(['en' => 'Manama', 'de' => 'Manama']), 'country_id' => 77, 'region_id' => null, 'population' => 650604, 'lat' => 26.22787000, 'lng' => 50.58565000, 'is_capital' => true, 'created_at' => now(), 'updated_at' => now()], // Bahrain - Capital
            ['id' => 1115, 'name_translations' => json_encode(['en' => 'Muscat', 'de' => 'Maskat']), 'country_id' => 102, 'region_id' => null, 'population' => 1421409, 'lat' => 23.58413000, 'lng' => 58.40778000, 'is_capital' => true, 'created_at' => now(), 'updated_at' => now()], // Oman - Capital
            ['id' => 1116, 'name_translations' => json_encode(['en' => 'Sanaa', 'de' => 'Sanaa']), 'country_id' => 118, 'region_id' => null, 'population' => 2545000, 'lat' => 15.36957000, 'lng' => 44.19110000, 'is_capital' => true, 'created_at' => now(), 'updated_at' => now()], // Yemen - Capital
            ['id' => 1117, 'name_translations' => json_encode(['en' => 'Kabul', 'de' => 'Kabul']), 'country_id' => 73, 'region_id' => null, 'population' => 4273156, 'lat' => 34.52813000, 'lng' => 69.17233000, 'is_capital' => true, 'created_at' => now(), 'updated_at' => now()], // Afghanistan - Capital
            ['id' => 1118, 'name_translations' => json_encode(['en' => 'Baku', 'de' => 'Baku']), 'country_id' => 75, 'region_id' => null, 'population' => 2293400, 'lat' => 40.40926000, 'lng' => 49.86707000, 'is_capital' => true, 'created_at' => now(), 'updated_at' => now()], // Azerbaijan - Capital
            ['id' => 1119, 'name_translations' => json_encode(['en' => 'Mashhad', 'de' => 'Maschhad']), 'country_id' => 86, 'region_id' => null, 'population' => 3312090, 'lat' => 36.29780000, 'lng' => 59.60560000, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // Iran
            ['id' => 1120, 'name_translations' => json_encode(['en' => 'Karaj', 'de' => 'Karadsch']), 'country_id' => 86, 'region_id' => null, 'population' => 1968312, 'lat' => 35.83266000, 'lng' => 51.01040000, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // Iran
            ['id' => 1121, 'name_translations' => json_encode(['en' => 'Tel Aviv', 'de' => 'Tel Aviv']), 'country_id' => 83, 'region_id' => null, 'population' => 460613, 'lat' => 32.08530000, 'lng' => 34.78180000, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // Israel
            ['id' => 1122, 'name_translations' => json_encode(['en' => 'Jeddah', 'de' => 'Dschidda']), 'country_id' => 107, 'region_id' => null, 'population' => 4697000, 'lat' => 21.48530000, 'lng' => 39.19240000, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // Saudi Arabia
            ['id' => 1123, 'name_translations' => json_encode(['en' => 'Mecca', 'de' => 'Mekka']), 'country_id' => 107, 'region_id' => null, 'population' => 2385509, 'lat' => 21.38909000, 'lng' => 39.85791000, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // Saudi Arabia
            ['id' => 1124, 'name_translations' => json_encode(['en' => 'Medina', 'de' => 'Medina']), 'country_id' => 107, 'region_id' => null, 'population' => 1488782, 'lat' => 24.52680000, 'lng' => 39.60540000, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // Saudi Arabia
            ['id' => 1125, 'name_translations' => json_encode(['en' => 'Shiraz', 'de' => 'Schiraz']), 'country_id' => 86, 'region_id' => null, 'population' => 1869001, 'lat' => 29.59180000, 'lng' => 52.58380000, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // Iran
            ['id' => 1126, 'name_translations' => json_encode(['en' => 'Tabriz', 'de' => 'Täbris']), 'country_id' => 86, 'region_id' => null, 'population' => 1733033, 'lat' => 38.08010000, 'lng' => 46.29190000, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // Iran
            ['id' => 1127, 'name_translations' => json_encode(['en' => 'Basra', 'de' => 'Basra']), 'country_id' => 85, 'region_id' => null, 'population' => 2600000, 'lat' => 30.53320000, 'lng' => 47.79750000, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // Iraq
            ['id' => 1128, 'name_translations' => json_encode(['en' => 'Mosul', 'de' => 'Mossul']), 'country_id' => 85, 'region_id' => null, 'population' => 1739800, 'lat' => 36.33500000, 'lng' => 43.11890000, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // Iraq
            ['id' => 1129, 'name_translations' => json_encode(['en' => 'Aleppo', 'de' => 'Aleppo']), 'country_id' => 109, 'region_id' => null, 'population' => 2098210, 'lat' => 36.20124000, 'lng' => 37.16117000, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // Syria
            ['id' => 1130, 'name_translations' => json_encode(['en' => 'Tripoli', 'de' => 'Tripoli']), 'country_id' => 95, 'region_id' => null, 'population' => 500000, 'lat' => 34.43330000, 'lng' => 35.83330000, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // Lebanon
            ['id' => 1131, 'name_translations' => json_encode(['en' => 'Petra', 'de' => 'Petra']), 'country_id' => 87, 'region_id' => null, 'population' => 20000, 'lat' => 30.32940000, 'lng' => 35.44220000, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // Jordan
            ['id' => 1132, 'name_translations' => json_encode(['en' => 'Haifa', 'de' => 'Haifa']), 'country_id' => 83, 'region_id' => null, 'population' => 285316, 'lat' => 32.79410000, 'lng' => 34.98960000, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // Israel
            ['id' => 1133, 'name_translations' => json_encode(['en' => 'Gaza City', 'de' => 'Gaza-Stadt']), 'country_id' => 105, 'region_id' => null, 'population' => 590481, 'lat' => 31.50440000, 'lng' => 34.46650000, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // Palestine
            ['id' => 1134, 'name_translations' => json_encode(['en' => 'Ramallah', 'de' => 'Ramallah']), 'country_id' => 105, 'region_id' => null, 'population' => 38998, 'lat' => 31.90260000, 'lng' => 35.20660000, 'is_capital' => true, 'created_at' => now(), 'updated_at' => now()], // Palestine - Capital
            ['id' => 1135, 'name_translations' => json_encode(['en' => 'Aden', 'de' => 'Aden']), 'country_id' => 118, 'region_id' => null, 'population' => 1080000, 'lat' => 12.77944000, 'lng' => 45.03670000, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // Yemen
            ['id' => 1136, 'name_translations' => json_encode(['en' => 'Kandahar', 'de' => 'Kandahar']), 'country_id' => 73, 'region_id' => null, 'population' => 614118, 'lat' => 31.61320000, 'lng' => 65.70230000, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // Afghanistan
            ['id' => 1137, 'name_translations' => json_encode(['en' => 'Herat', 'de' => 'Herat']), 'country_id' => 73, 'region_id' => null, 'population' => 574276, 'lat' => 34.34820000, 'lng' => 62.19970000, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // Afghanistan
            ['id' => 1138, 'name_translations' => json_encode(['en' => 'Bursa', 'de' => 'Bursa']), 'country_id' => 114, 'region_id' => null, 'population' => 3056120, 'lat' => 40.18260000, 'lng' => 29.06690000, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // Turkey
            ['id' => 1139, 'name_translations' => json_encode(['en' => 'Antalya', 'de' => 'Antalya']), 'country_id' => 114, 'region_id' => null, 'population' => 2548308, 'lat' => 36.88414000, 'lng' => 30.70563000, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // Turkey
            ['id' => 1140, 'name_translations' => json_encode(['en' => 'Dammam', 'de' => 'Dammam']), 'country_id' => 107, 'region_id' => null, 'population' => 1532300, 'lat' => 26.43442000, 'lng' => 50.10326000, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // Saudi Arabia
            ['id' => 1141, 'name_translations' => json_encode(['en' => 'Taif', 'de' => 'Taif']), 'country_id' => 107, 'region_id' => null, 'population' => 1200000, 'lat' => 21.27020000, 'lng' => 40.41540000, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // Saudi Arabia
            ['id' => 1142, 'name_translations' => json_encode(['en' => 'Ganja', 'de' => 'Gandja']), 'country_id' => 75, 'region_id' => null, 'population' => 335600, 'lat' => 40.68280000, 'lng' => 46.36080000, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // Azerbaijan
            ['id' => 1143, 'name_translations' => json_encode(['en' => 'Sumgait', 'de' => 'Sumgait']), 'country_id' => 75, 'region_id' => null, 'population' => 341200, 'lat' => 40.58970000, 'lng' => 49.66900000, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // Azerbaijan
            ['id' => 1144, 'name_translations' => json_encode(['en' => 'Salalah', 'de' => 'Salalah']), 'country_id' => 102, 'region_id' => null, 'population' => 331949, 'lat' => 17.01532000, 'lng' => 54.09244000, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // Oman
            ['id' => 1145, 'name_translations' => json_encode(['en' => 'Taiz', 'de' => 'Taiz']), 'country_id' => 118, 'region_id' => null, 'population' => 615222, 'lat' => 13.57950000, 'lng' => 44.02090000, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // Yemen
            ['id' => 1146, 'name_translations' => json_encode(['en' => 'Balkh', 'de' => 'Balch']), 'country_id' => 73, 'region_id' => null, 'population' => 138594, 'lat' => 36.75770000, 'lng' => 66.89730000, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // Afghanistan
            ['id' => 1147, 'name_translations' => json_encode(['en' => 'Yazd', 'de' => 'Yazd']), 'country_id' => 86, 'region_id' => null, 'population' => 529673, 'lat' => 31.89722000, 'lng' => 54.36750000, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // Iran
            ['id' => 1148, 'name_translations' => json_encode(['en' => 'Qom', 'de' => 'Qom']), 'country_id' => 86, 'region_id' => null, 'population' => 1292283, 'lat' => 34.64010000, 'lng' => 50.87580000, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // Iran
            ['id' => 1149, 'name_translations' => json_encode(['en' => 'Edirne', 'de' => 'Edirne']), 'country_id' => 114, 'region_id' => null, 'population' => 180327, 'lat' => 41.67710000, 'lng' => 26.55597000, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // Turkey
            ['id' => 1150, 'name_translations' => json_encode(['en' => 'Trabzon', 'de' => 'Trabzon']), 'country_id' => 114, 'region_id' => null, 'population' => 758237, 'lat' => 41.00145000, 'lng' => 39.71694000, 'is_capital' => false, 'created_at' => now(), 'updated_at' => now()], // Turkey
        ];
    }
}