<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesSeeder extends Seeder
{
    public function run(): void
    {
        $countries = $this->getAllCountries();
        
        foreach ($countries as $country) {
            DB::table('countries')->updateOrInsert(
                ['iso_code' => $country['iso_code']],
                $country
            );
        }
    }

    private function getAllCountries(): array
    {
        return [
            // Europa (continent_id: 1)
            ['iso_code' => 'AD', 'iso3_code' => 'AND', 'name_translations' => json_encode(['en' => 'Andorra', 'de' => 'Andorra']), 'continent_id' => 1, 'is_eu_member' => false, 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'phone_prefix' => '+376', 'languages' => json_encode(['ca']), 'timezone' => 'Europe/Andorra', 'population' => 79000, 'area_km2' => 468.00, 'lat' => 42.5063, 'lng' => 1.5218, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'AL', 'iso3_code' => 'ALB', 'name_translations' => json_encode(['en' => 'Albania', 'de' => 'Albanien']), 'continent_id' => 1, 'is_eu_member' => false, 'currency_code' => 'ALL', 'currency_name' => 'Albanian Lek', 'currency_symbol' => 'L', 'phone_prefix' => '+355', 'languages' => json_encode(['sq']), 'timezone' => 'Europe/Tirane', 'population' => 2877000, 'area_km2' => 28748.00, 'lat' => 41.1533, 'lng' => 20.1683, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'AT', 'iso3_code' => 'AUT', 'name_translations' => json_encode(['en' => 'Austria', 'de' => 'Österreich']), 'continent_id' => 1, 'is_eu_member' => true, 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'phone_prefix' => '+43', 'languages' => json_encode(['de']), 'timezone' => 'Europe/Vienna', 'population' => 9006000, 'area_km2' => 83871.00, 'lat' => 47.5162, 'lng' => 14.5501, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'BA', 'iso3_code' => 'BIH', 'name_translations' => json_encode(['en' => 'Bosnia and Herzegovina', 'de' => 'Bosnien und Herzegowina']), 'continent_id' => 1, 'is_eu_member' => false, 'currency_code' => 'BAM', 'currency_name' => 'Bosnia and Herzegovina Convertible Mark', 'currency_symbol' => 'KM', 'phone_prefix' => '+387', 'languages' => json_encode(['bs', 'hr', 'sr']), 'timezone' => 'Europe/Sarajevo', 'population' => 3281000, 'area_km2' => 51197.00, 'lat' => 43.9159, 'lng' => 17.6791, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'BE', 'iso3_code' => 'BEL', 'name_translations' => json_encode(['en' => 'Belgium', 'de' => 'Belgien']), 'continent_id' => 1, 'is_eu_member' => true, 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'phone_prefix' => '+32', 'languages' => json_encode(['nl', 'fr', 'de']), 'timezone' => 'Europe/Brussels', 'population' => 11590000, 'area_km2' => 30528.00, 'lat' => 50.5039, 'lng' => 4.4699, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'BG', 'iso3_code' => 'BGR', 'name_translations' => json_encode(['en' => 'Bulgaria', 'de' => 'Bulgarien']), 'continent_id' => 1, 'is_eu_member' => true, 'currency_code' => 'BGN', 'currency_name' => 'Bulgarian Lev', 'currency_symbol' => 'лв', 'phone_prefix' => '+359', 'languages' => json_encode(['bg']), 'timezone' => 'Europe/Sofia', 'population' => 6948000, 'area_km2' => 110879.00, 'lat' => 42.7339, 'lng' => 25.4858, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'BY', 'iso3_code' => 'BLR', 'name_translations' => json_encode(['en' => 'Belarus', 'de' => 'Belarus']), 'continent_id' => 1, 'is_eu_member' => false, 'currency_code' => 'BYN', 'currency_name' => 'Belarusian Ruble', 'currency_symbol' => 'Br', 'phone_prefix' => '+375', 'languages' => json_encode(['be', 'ru']), 'timezone' => 'Europe/Minsk', 'population' => 9449000, 'area_km2' => 207600.00, 'lat' => 53.7098, 'lng' => 27.9534, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'CH', 'iso3_code' => 'CHE', 'name_translations' => json_encode(['en' => 'Switzerland', 'de' => 'Schweiz']), 'continent_id' => 1, 'is_eu_member' => false, 'currency_code' => 'CHF', 'currency_name' => 'Swiss Franc', 'currency_symbol' => 'Fr', 'phone_prefix' => '+41', 'languages' => json_encode(['de', 'fr', 'it', 'rm']), 'timezone' => 'Europe/Zurich', 'population' => 8655000, 'area_km2' => 41285.00, 'lat' => 46.8182, 'lng' => 8.2275, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'CY', 'iso3_code' => 'CYP', 'name_translations' => json_encode(['en' => 'Cyprus', 'de' => 'Zypern']), 'continent_id' => 1, 'is_eu_member' => true, 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'phone_prefix' => '+357', 'languages' => json_encode(['el', 'tr']), 'timezone' => 'Asia/Nicosia', 'population' => 1207000, 'area_km2' => 9251.00, 'lat' => 35.1264, 'lng' => 33.4299, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'CZ', 'iso3_code' => 'CZE', 'name_translations' => json_encode(['en' => 'Czech Republic', 'de' => 'Tschechische Republik']), 'continent_id' => 1, 'is_eu_member' => true, 'currency_code' => 'CZK', 'currency_name' => 'Czech Koruna', 'currency_symbol' => 'Kč', 'phone_prefix' => '+420', 'languages' => json_encode(['cs']), 'timezone' => 'Europe/Prague', 'population' => 10708000, 'area_km2' => 78867.00, 'lat' => 49.8175, 'lng' => 15.4730, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'DE', 'iso3_code' => 'DEU', 'name_translations' => json_encode(['en' => 'Germany', 'de' => 'Deutschland']), 'continent_id' => 1, 'is_eu_member' => true, 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'phone_prefix' => '+49', 'languages' => json_encode(['de']), 'timezone' => 'Europe/Berlin', 'population' => 83784000, 'area_km2' => 357022.00, 'lat' => 51.1657, 'lng' => 10.4515, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'DK', 'iso3_code' => 'DNK', 'name_translations' => json_encode(['en' => 'Denmark', 'de' => 'Dänemark']), 'continent_id' => 1, 'is_eu_member' => true, 'currency_code' => 'DKK', 'currency_name' => 'Danish Krone', 'currency_symbol' => 'kr', 'phone_prefix' => '+45', 'languages' => json_encode(['da']), 'timezone' => 'Europe/Copenhagen', 'population' => 5792000, 'area_km2' => 43094.00, 'lat' => 56.2639, 'lng' => 9.5018, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'EE', 'iso3_code' => 'EST', 'name_translations' => json_encode(['en' => 'Estonia', 'de' => 'Estland']), 'continent_id' => 1, 'is_eu_member' => true, 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'phone_prefix' => '+372', 'languages' => json_encode(['et']), 'timezone' => 'Europe/Tallinn', 'population' => 1326000, 'area_km2' => 45228.00, 'lat' => 58.5953, 'lng' => 25.0136, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'ES', 'iso3_code' => 'ESP', 'name_translations' => json_encode(['en' => 'Spain', 'de' => 'Spanien']), 'continent_id' => 1, 'is_eu_member' => true, 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'phone_prefix' => '+34', 'languages' => json_encode(['es']), 'timezone' => 'Europe/Madrid', 'population' => 46755000, 'area_km2' => 505370.00, 'lat' => 40.4637, 'lng' => -3.7492, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'FI', 'iso3_code' => 'FIN', 'name_translations' => json_encode(['en' => 'Finland', 'de' => 'Finnland']), 'continent_id' => 1, 'is_eu_member' => true, 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'phone_prefix' => '+358', 'languages' => json_encode(['fi', 'sv']), 'timezone' => 'Europe/Helsinki', 'population' => 5541000, 'area_km2' => 338424.00, 'lat' => 61.9241, 'lng' => 25.7482, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'FR', 'iso3_code' => 'FRA', 'name_translations' => json_encode(['en' => 'France', 'de' => 'Frankreich']), 'continent_id' => 1, 'is_eu_member' => true, 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'phone_prefix' => '+33', 'languages' => json_encode(['fr']), 'timezone' => 'Europe/Paris', 'population' => 65274000, 'area_km2' => 643801.00, 'lat' => 46.2276, 'lng' => 2.2137, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'GB', 'iso3_code' => 'GBR', 'name_translations' => json_encode(['en' => 'United Kingdom', 'de' => 'Vereinigtes Königreich']), 'continent_id' => 1, 'is_eu_member' => false, 'currency_code' => 'GBP', 'currency_name' => 'British Pound Sterling', 'currency_symbol' => '£', 'phone_prefix' => '+44', 'languages' => json_encode(['en']), 'timezone' => 'Europe/London', 'population' => 67886000, 'area_km2' => 243610.00, 'lat' => 55.3781, 'lng' => -3.4360, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'GR', 'iso3_code' => 'GRC', 'name_translations' => json_encode(['en' => 'Greece', 'de' => 'Griechenland']), 'continent_id' => 1, 'is_eu_member' => true, 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'phone_prefix' => '+30', 'languages' => json_encode(['el']), 'timezone' => 'Europe/Athens', 'population' => 10423000, 'area_km2' => 131957.00, 'lat' => 39.0742, 'lng' => 21.8243, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'HR', 'iso3_code' => 'HRV', 'name_translations' => json_encode(['en' => 'Croatia', 'de' => 'Kroatien']), 'continent_id' => 1, 'is_eu_member' => true, 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'phone_prefix' => '+385', 'languages' => json_encode(['hr']), 'timezone' => 'Europe/Zagreb', 'population' => 4105000, 'area_km2' => 56594.00, 'lat' => 45.1000, 'lng' => 15.2000, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'HU', 'iso3_code' => 'HUN', 'name_translations' => json_encode(['en' => 'Hungary', 'de' => 'Ungarn']), 'continent_id' => 1, 'is_eu_member' => true, 'currency_code' => 'HUF', 'currency_name' => 'Hungarian Forint', 'currency_symbol' => 'Ft', 'phone_prefix' => '+36', 'languages' => json_encode(['hu']), 'timezone' => 'Europe/Budapest', 'population' => 9660000, 'area_km2' => 93028.00, 'lat' => 47.1625, 'lng' => 19.5033, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'IE', 'iso3_code' => 'IRL', 'name_translations' => json_encode(['en' => 'Ireland', 'de' => 'Irland']), 'continent_id' => 1, 'is_eu_member' => true, 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'phone_prefix' => '+353', 'languages' => json_encode(['en', 'ga']), 'timezone' => 'Europe/Dublin', 'population' => 4938000, 'area_km2' => 70273.00, 'lat' => 53.4129, 'lng' => -8.2439, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'IS', 'iso3_code' => 'ISL', 'name_translations' => json_encode(['en' => 'Iceland', 'de' => 'Island']), 'continent_id' => 1, 'is_eu_member' => false, 'currency_code' => 'ISK', 'currency_name' => 'Icelandic Króna', 'currency_symbol' => 'kr', 'phone_prefix' => '+354', 'languages' => json_encode(['is']), 'timezone' => 'Atlantic/Reykjavik', 'population' => 341000, 'area_km2' => 103000.00, 'lat' => 64.9631, 'lng' => -19.0208, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'IT', 'iso3_code' => 'ITA', 'name_translations' => json_encode(['en' => 'Italy', 'de' => 'Italien']), 'continent_id' => 1, 'is_eu_member' => true, 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'phone_prefix' => '+39', 'languages' => json_encode(['it']), 'timezone' => 'Europe/Rome', 'population' => 60462000, 'area_km2' => 301340.00, 'lat' => 41.8719, 'lng' => 12.5674, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'LI', 'iso3_code' => 'LIE', 'name_translations' => json_encode(['en' => 'Liechtenstein', 'de' => 'Liechtenstein']), 'continent_id' => 1, 'is_eu_member' => false, 'currency_code' => 'CHF', 'currency_name' => 'Swiss Franc', 'currency_symbol' => 'Fr', 'phone_prefix' => '+423', 'languages' => json_encode(['de']), 'timezone' => 'Europe/Vaduz', 'population' => 38000, 'area_km2' => 160.00, 'lat' => 47.1660, 'lng' => 9.5554, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'LT', 'iso3_code' => 'LTU', 'name_translations' => json_encode(['en' => 'Lithuania', 'de' => 'Litauen']), 'continent_id' => 1, 'is_eu_member' => true, 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'phone_prefix' => '+370', 'languages' => json_encode(['lt']), 'timezone' => 'Europe/Vilnius', 'population' => 2722000, 'area_km2' => 65300.00, 'lat' => 55.1694, 'lng' => 23.8813, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'LU', 'iso3_code' => 'LUX', 'name_translations' => json_encode(['en' => 'Luxembourg', 'de' => 'Luxemburg']), 'continent_id' => 1, 'is_eu_member' => true, 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'phone_prefix' => '+352', 'languages' => json_encode(['lb', 'fr', 'de']), 'timezone' => 'Europe/Luxembourg', 'population' => 625000, 'area_km2' => 2586.00, 'lat' => 49.8153, 'lng' => 6.1296, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'LV', 'iso3_code' => 'LVA', 'name_translations' => json_encode(['en' => 'Latvia', 'de' => 'Lettland']), 'continent_id' => 1, 'is_eu_member' => true, 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'phone_prefix' => '+371', 'languages' => json_encode(['lv']), 'timezone' => 'Europe/Riga', 'population' => 1886000, 'area_km2' => 64589.00, 'lat' => 56.8796, 'lng' => 24.6032, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'MC', 'iso3_code' => 'MCO', 'name_translations' => json_encode(['en' => 'Monaco', 'de' => 'Monaco']), 'continent_id' => 1, 'is_eu_member' => false, 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'phone_prefix' => '+377', 'languages' => json_encode(['fr']), 'timezone' => 'Europe/Monaco', 'population' => 39000, 'area_km2' => 2.02, 'lat' => 43.7384, 'lng' => 7.4246, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'MD', 'iso3_code' => 'MDA', 'name_translations' => json_encode(['en' => 'Moldova', 'de' => 'Moldawien']), 'continent_id' => 1, 'is_eu_member' => false, 'currency_code' => 'MDL', 'currency_name' => 'Moldovan Leu', 'currency_symbol' => 'L', 'phone_prefix' => '+373', 'languages' => json_encode(['ro']), 'timezone' => 'Europe/Chisinau', 'population' => 4034000, 'area_km2' => 33851.00, 'lat' => 47.4116, 'lng' => 28.3699, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'ME', 'iso3_code' => 'MNE', 'name_translations' => json_encode(['en' => 'Montenegro', 'de' => 'Montenegro']), 'continent_id' => 1, 'is_eu_member' => false, 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'phone_prefix' => '+382', 'languages' => json_encode(['sr']), 'timezone' => 'Europe/Podgorica', 'population' => 628000, 'area_km2' => 13812.00, 'lat' => 42.7087, 'lng' => 19.3744, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'MK', 'iso3_code' => 'MKD', 'name_translations' => json_encode(['en' => 'North Macedonia', 'de' => 'Nordmazedonien']), 'continent_id' => 1, 'is_eu_member' => false, 'currency_code' => 'MKD', 'currency_name' => 'Macedonian Denar', 'currency_symbol' => 'ден', 'phone_prefix' => '+389', 'languages' => json_encode(['mk']), 'timezone' => 'Europe/Skopje', 'population' => 2083000, 'area_km2' => 25713.00, 'lat' => 41.6086, 'lng' => 21.7453, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'MT', 'iso3_code' => 'MLT', 'name_translations' => json_encode(['en' => 'Malta', 'de' => 'Malta']), 'continent_id' => 1, 'is_eu_member' => true, 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'phone_prefix' => '+356', 'languages' => json_encode(['mt', 'en']), 'timezone' => 'Europe/Malta', 'population' => 441000, 'area_km2' => 316.00, 'lat' => 35.9375, 'lng' => 14.3754, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'NL', 'iso3_code' => 'NLD', 'name_translations' => json_encode(['en' => 'Netherlands', 'de' => 'Niederlande']), 'continent_id' => 1, 'is_eu_member' => true, 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'phone_prefix' => '+31', 'languages' => json_encode(['nl']), 'timezone' => 'Europe/Amsterdam', 'population' => 17135000, 'area_km2' => 41543.00, 'lat' => 52.1326, 'lng' => 5.2913, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'NO', 'iso3_code' => 'NOR', 'name_translations' => json_encode(['en' => 'Norway', 'de' => 'Norwegen']), 'continent_id' => 1, 'is_eu_member' => false, 'currency_code' => 'NOK', 'currency_name' => 'Norwegian Krone', 'currency_symbol' => 'kr', 'phone_prefix' => '+47', 'languages' => json_encode(['no']), 'timezone' => 'Europe/Oslo', 'population' => 5421000, 'area_km2' => 323802.00, 'lat' => 60.4720, 'lng' => 8.4689, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'PL', 'iso3_code' => 'POL', 'name_translations' => json_encode(['en' => 'Poland', 'de' => 'Polen']), 'continent_id' => 1, 'is_eu_member' => true, 'currency_code' => 'PLN', 'currency_name' => 'Polish Złoty', 'currency_symbol' => 'zł', 'phone_prefix' => '+48', 'languages' => json_encode(['pl']), 'timezone' => 'Europe/Warsaw', 'population' => 37847000, 'area_km2' => 312685.00, 'lat' => 51.9194, 'lng' => 19.1451, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'PT', 'iso3_code' => 'PRT', 'name_translations' => json_encode(['en' => 'Portugal', 'de' => 'Portugal']), 'continent_id' => 1, 'is_eu_member' => true, 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'phone_prefix' => '+351', 'languages' => json_encode(['pt']), 'timezone' => 'Europe/Lisbon', 'population' => 10196000, 'area_km2' => 92090.00, 'lat' => 39.3999, 'lng' => -8.2245, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'RO', 'iso3_code' => 'ROU', 'name_translations' => json_encode(['en' => 'Romania', 'de' => 'Rumänien']), 'continent_id' => 1, 'is_eu_member' => true, 'currency_code' => 'RON', 'currency_name' => 'Romanian Leu', 'currency_symbol' => 'lei', 'phone_prefix' => '+40', 'languages' => json_encode(['ro']), 'timezone' => 'Europe/Bucharest', 'population' => 19238000, 'area_km2' => 238391.00, 'lat' => 45.9432, 'lng' => 24.9668, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'RS', 'iso3_code' => 'SRB', 'name_translations' => json_encode(['en' => 'Serbia', 'de' => 'Serbien']), 'continent_id' => 1, 'is_eu_member' => false, 'currency_code' => 'RSD', 'currency_name' => 'Serbian Dinar', 'currency_symbol' => 'РСД', 'phone_prefix' => '+381', 'languages' => json_encode(['sr']), 'timezone' => 'Europe/Belgrade', 'population' => 8737000, 'area_km2' => 77474.00, 'lat' => 44.0165, 'lng' => 21.0059, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'RU', 'iso3_code' => 'RUS', 'name_translations' => json_encode(['en' => 'Russia', 'de' => 'Russland']), 'continent_id' => 1, 'is_eu_member' => false, 'currency_code' => 'RUB', 'currency_name' => 'Russian Ruble', 'currency_symbol' => '₽', 'phone_prefix' => '+7', 'languages' => json_encode(['ru']), 'timezone' => 'Europe/Moscow', 'population' => 145934000, 'area_km2' => 17098242.00, 'lat' => 61.5240, 'lng' => 105.3188, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'SE', 'iso3_code' => 'SWE', 'name_translations' => json_encode(['en' => 'Sweden', 'de' => 'Schweden']), 'continent_id' => 1, 'is_eu_member' => true, 'currency_code' => 'SEK', 'currency_name' => 'Swedish Krona', 'currency_symbol' => 'kr', 'phone_prefix' => '+46', 'languages' => json_encode(['sv']), 'timezone' => 'Europe/Stockholm', 'population' => 10099000, 'area_km2' => 450295.00, 'lat' => 60.1282, 'lng' => 18.6435, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'SI', 'iso3_code' => 'SVN', 'name_translations' => json_encode(['en' => 'Slovenia', 'de' => 'Slowenien']), 'continent_id' => 1, 'is_eu_member' => true, 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'phone_prefix' => '+386', 'languages' => json_encode(['sl']), 'timezone' => 'Europe/Ljubljana', 'population' => 2079000, 'area_km2' => 20273.00, 'lat' => 46.1512, 'lng' => 14.9955, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'SK', 'iso3_code' => 'SVK', 'name_translations' => json_encode(['en' => 'Slovakia', 'de' => 'Slowakei']), 'continent_id' => 1, 'is_eu_member' => true, 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'phone_prefix' => '+421', 'languages' => json_encode(['sk']), 'timezone' => 'Europe/Bratislava', 'population' => 5460000, 'area_km2' => 49035.00, 'lat' => 48.6690, 'lng' => 19.6990, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'SM', 'iso3_code' => 'SMR', 'name_translations' => json_encode(['en' => 'San Marino', 'de' => 'San Marino']), 'continent_id' => 1, 'is_eu_member' => false, 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'phone_prefix' => '+378', 'languages' => json_encode(['it']), 'timezone' => 'Europe/San_Marino', 'population' => 34000, 'area_km2' => 61.00, 'lat' => 43.9424, 'lng' => 12.4578, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'UA', 'iso3_code' => 'UKR', 'name_translations' => json_encode(['en' => 'Ukraine', 'de' => 'Ukraine']), 'continent_id' => 1, 'is_eu_member' => false, 'currency_code' => 'UAH', 'currency_name' => 'Ukrainian Hryvnia', 'currency_symbol' => '₴', 'phone_prefix' => '+380', 'languages' => json_encode(['uk']), 'timezone' => 'Europe/Kiev', 'population' => 43734000, 'area_km2' => 603550.00, 'lat' => 48.3794, 'lng' => 31.1656, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'VA', 'iso3_code' => 'VAT', 'name_translations' => json_encode(['en' => 'Vatican City', 'de' => 'Vatikanstadt']), 'continent_id' => 1, 'is_eu_member' => false, 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => '€', 'phone_prefix' => '+379', 'languages' => json_encode(['it', 'la']), 'timezone' => 'Europe/Vatican', 'population' => 801, 'area_km2' => 0.44, 'lat' => 41.9029, 'lng' => 12.4534, 'created_at' => now(), 'updated_at' => now()],

            // Asien (continent_id: 2)
            ['iso_code' => 'AF', 'iso3_code' => 'AFG', 'name_translations' => json_encode(['en' => 'Afghanistan', 'de' => 'Afghanistan']), 'continent_id' => 2, 'is_eu_member' => false, 'currency_code' => 'AFN', 'currency_name' => 'Afghan Afghani', 'currency_symbol' => '؋', 'phone_prefix' => '+93', 'languages' => json_encode(['ps', 'fa']), 'timezone' => 'Asia/Kabul', 'population' => 38928000, 'area_km2' => 652230.00, 'lat' => 33.9391, 'lng' => 67.7100, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'AM', 'iso3_code' => 'ARM', 'name_translations' => json_encode(['en' => 'Armenia', 'de' => 'Armenien']), 'continent_id' => 2, 'is_eu_member' => false, 'currency_code' => 'AMD', 'currency_name' => 'Armenian Dram', 'currency_symbol' => '֏', 'phone_prefix' => '+374', 'languages' => json_encode(['hy']), 'timezone' => 'Asia/Yerevan', 'population' => 2963000, 'area_km2' => 29743.00, 'lat' => 40.0691, 'lng' => 45.0382, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'AZ', 'iso3_code' => 'AZE', 'name_translations' => json_encode(['en' => 'Azerbaijan', 'de' => 'Aserbaidschan']), 'continent_id' => 2, 'is_eu_member' => false, 'currency_code' => 'AZN', 'currency_name' => 'Azerbaijani Manat', 'currency_symbol' => '₼', 'phone_prefix' => '+994', 'languages' => json_encode(['az']), 'timezone' => 'Asia/Baku', 'population' => 10139000, 'area_km2' => 86600.00, 'lat' => 40.1431, 'lng' => 47.5769, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'BD', 'iso3_code' => 'BGD', 'name_translations' => json_encode(['en' => 'Bangladesh', 'de' => 'Bangladesch']), 'continent_id' => 2, 'is_eu_member' => false, 'currency_code' => 'BDT', 'currency_name' => 'Bangladeshi Taka', 'currency_symbol' => '৳', 'phone_prefix' => '+880', 'languages' => json_encode(['bn']), 'timezone' => 'Asia/Dhaka', 'population' => 164689000, 'area_km2' => 147570.00, 'lat' => 23.6850, 'lng' => 90.3563, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'BH', 'iso3_code' => 'BHR', 'name_translations' => json_encode(['en' => 'Bahrain', 'de' => 'Bahrain']), 'continent_id' => 2, 'is_eu_member' => false, 'currency_code' => 'BHD', 'currency_name' => 'Bahraini Dinar', 'currency_symbol' => '.د.ب', 'phone_prefix' => '+973', 'languages' => json_encode(['ar']), 'timezone' => 'Asia/Bahrain', 'population' => 1702000, 'area_km2' => 765.00, 'lat' => 25.9304, 'lng' => 50.6378, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'BN', 'iso3_code' => 'BRN', 'name_translations' => json_encode(['en' => 'Brunei', 'de' => 'Brunei']), 'continent_id' => 2, 'is_eu_member' => false, 'currency_code' => 'BND', 'currency_name' => 'Brunei Dollar', 'currency_symbol' => 'B$', 'phone_prefix' => '+673', 'languages' => json_encode(['ms']), 'timezone' => 'Asia/Brunei', 'population' => 437000, 'area_km2' => 5765.00, 'lat' => 4.5353, 'lng' => 114.7277, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'BT', 'iso3_code' => 'BTN', 'name_translations' => json_encode(['en' => 'Bhutan', 'de' => 'Bhutan']), 'continent_id' => 2, 'is_eu_member' => false, 'currency_code' => 'BTN', 'currency_name' => 'Bhutanese Ngultrum', 'currency_symbol' => 'Nu.', 'phone_prefix' => '+975', 'languages' => json_encode(['dz']), 'timezone' => 'Asia/Thimphu', 'population' => 772000, 'area_km2' => 38394.00, 'lat' => 27.5142, 'lng' => 90.4336, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'CN', 'iso3_code' => 'CHN', 'name_translations' => json_encode(['en' => 'China', 'de' => 'China']), 'continent_id' => 2, 'is_eu_member' => false, 'currency_code' => 'CNY', 'currency_name' => 'Chinese Yuan', 'currency_symbol' => '¥', 'phone_prefix' => '+86', 'languages' => json_encode(['zh']), 'timezone' => 'Asia/Shanghai', 'population' => 1439324000, 'area_km2' => 9596960.00, 'lat' => 35.8617, 'lng' => 104.1954, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'GE', 'iso3_code' => 'GEO', 'name_translations' => json_encode(['en' => 'Georgia', 'de' => 'Georgien']), 'continent_id' => 2, 'is_eu_member' => false, 'currency_code' => 'GEL', 'currency_name' => 'Georgian Lari', 'currency_symbol' => '₾', 'phone_prefix' => '+995', 'languages' => json_encode(['ka']), 'timezone' => 'Asia/Tbilisi', 'population' => 3989000, 'area_km2' => 69700.00, 'lat' => 42.3154, 'lng' => 43.3569, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'ID', 'iso3_code' => 'IDN', 'name_translations' => json_encode(['en' => 'Indonesia', 'de' => 'Indonesien']), 'continent_id' => 2, 'is_eu_member' => false, 'currency_code' => 'IDR', 'currency_name' => 'Indonesian Rupiah', 'currency_symbol' => 'Rp', 'phone_prefix' => '+62', 'languages' => json_encode(['id']), 'timezone' => 'Asia/Jakarta', 'population' => 273524000, 'area_km2' => 1904569.00, 'lat' => -0.7893, 'lng' => 113.9213, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'IL', 'iso3_code' => 'ISR', 'name_translations' => json_encode(['en' => 'Israel', 'de' => 'Israel']), 'continent_id' => 2, 'is_eu_member' => false, 'currency_code' => 'ILS', 'currency_name' => 'Israeli New Shekel', 'currency_symbol' => '₪', 'phone_prefix' => '+972', 'languages' => json_encode(['he', 'ar']), 'timezone' => 'Asia/Jerusalem', 'population' => 8656000, 'area_km2' => 20770.00, 'lat' => 31.0461, 'lng' => 34.8516, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'IN', 'iso3_code' => 'IND', 'name_translations' => json_encode(['en' => 'India', 'de' => 'Indien']), 'continent_id' => 2, 'is_eu_member' => false, 'currency_code' => 'INR', 'currency_name' => 'Indian Rupee', 'currency_symbol' => '₹', 'phone_prefix' => '+91', 'languages' => json_encode(['hi', 'en']), 'timezone' => 'Asia/Kolkata', 'population' => 1380004000, 'area_km2' => 3287263.00, 'lat' => 20.5937, 'lng' => 78.9629, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'IQ', 'iso3_code' => 'IRQ', 'name_translations' => json_encode(['en' => 'Iraq', 'de' => 'Irak']), 'continent_id' => 2, 'is_eu_member' => false, 'currency_code' => 'IQD', 'currency_name' => 'Iraqi Dinar', 'currency_symbol' => 'ع.د', 'phone_prefix' => '+964', 'languages' => json_encode(['ar', 'ku']), 'timezone' => 'Asia/Baghdad', 'population' => 40223000, 'area_km2' => 438317.00, 'lat' => 33.2232, 'lng' => 43.6793, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'IR', 'iso3_code' => 'IRN', 'name_translations' => json_encode(['en' => 'Iran', 'de' => 'Iran']), 'continent_id' => 2, 'is_eu_member' => false, 'currency_code' => 'IRR', 'currency_name' => 'Iranian Rial', 'currency_symbol' => '﷼', 'phone_prefix' => '+98', 'languages' => json_encode(['fa']), 'timezone' => 'Asia/Tehran', 'population' => 83993000, 'area_km2' => 1648195.00, 'lat' => 32.4279, 'lng' => 53.6880, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'JO', 'iso3_code' => 'JOR', 'name_translations' => json_encode(['en' => 'Jordan', 'de' => 'Jordanien']), 'continent_id' => 2, 'is_eu_member' => false, 'currency_code' => 'JOD', 'currency_name' => 'Jordanian Dinar', 'currency_symbol' => 'د.ا', 'phone_prefix' => '+962', 'languages' => json_encode(['ar']), 'timezone' => 'Asia/Amman', 'population' => 10203000, 'area_km2' => 89342.00, 'lat' => 30.5852, 'lng' => 36.2384, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'JP', 'iso3_code' => 'JPN', 'name_translations' => json_encode(['en' => 'Japan', 'de' => 'Japan']), 'continent_id' => 2, 'is_eu_member' => false, 'currency_code' => 'JPY', 'currency_name' => 'Japanese Yen', 'currency_symbol' => '¥', 'phone_prefix' => '+81', 'languages' => json_encode(['ja']), 'timezone' => 'Asia/Tokyo', 'population' => 126476000, 'area_km2' => 377915.00, 'lat' => 36.2048, 'lng' => 138.2529, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'KG', 'iso3_code' => 'KGZ', 'name_translations' => json_encode(['en' => 'Kyrgyzstan', 'de' => 'Kirgisistan']), 'continent_id' => 2, 'is_eu_member' => false, 'currency_code' => 'KGS', 'currency_name' => 'Kyrgyzstani Som', 'currency_symbol' => 'лв', 'phone_prefix' => '+996', 'languages' => json_encode(['ky', 'ru']), 'timezone' => 'Asia/Bishkek', 'population' => 6524000, 'area_km2' => 199951.00, 'lat' => 41.2044, 'lng' => 74.7661, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'KH', 'iso3_code' => 'KHM', 'name_translations' => json_encode(['en' => 'Cambodia', 'de' => 'Kambodscha']), 'continent_id' => 2, 'is_eu_member' => false, 'currency_code' => 'KHR', 'currency_name' => 'Cambodian Riel', 'currency_symbol' => '៛', 'phone_prefix' => '+855', 'languages' => json_encode(['km']), 'timezone' => 'Asia/Phnom_Penh', 'population' => 16719000, 'area_km2' => 181035.00, 'lat' => 12.5657, 'lng' => 104.9910, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'KR', 'iso3_code' => 'KOR', 'name_translations' => json_encode(['en' => 'South Korea', 'de' => 'Südkorea']), 'continent_id' => 2, 'is_eu_member' => false, 'currency_code' => 'KRW', 'currency_name' => 'South Korean Won', 'currency_symbol' => '₩', 'phone_prefix' => '+82', 'languages' => json_encode(['ko']), 'timezone' => 'Asia/Seoul', 'population' => 51269000, 'area_km2' => 100210.00, 'lat' => 35.9078, 'lng' => 127.7669, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'KW', 'iso3_code' => 'KWT', 'name_translations' => json_encode(['en' => 'Kuwait', 'de' => 'Kuwait']), 'continent_id' => 2, 'is_eu_member' => false, 'currency_code' => 'KWD', 'currency_name' => 'Kuwaiti Dinar', 'currency_symbol' => 'د.ك', 'phone_prefix' => '+965', 'languages' => json_encode(['ar']), 'timezone' => 'Asia/Kuwait', 'population' => 4271000, 'area_km2' => 17818.00, 'lat' => 29.3117, 'lng' => 47.4818, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'KZ', 'iso3_code' => 'KAZ', 'name_translations' => json_encode(['en' => 'Kazakhstan', 'de' => 'Kasachstan']), 'continent_id' => 2, 'is_eu_member' => false, 'currency_code' => 'KZT', 'currency_name' => 'Kazakhstani Tenge', 'currency_symbol' => '₸', 'phone_prefix' => '+7', 'languages' => json_encode(['kk', 'ru']), 'timezone' => 'Asia/Almaty', 'population' => 18777000, 'area_km2' => 2724900.00, 'lat' => 48.0196, 'lng' => 66.9237, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'LA', 'iso3_code' => 'LAO', 'name_translations' => json_encode(['en' => 'Laos', 'de' => 'Laos']), 'continent_id' => 2, 'is_eu_member' => false, 'currency_code' => 'LAK', 'currency_name' => 'Lao Kip', 'currency_symbol' => '₭', 'phone_prefix' => '+856', 'languages' => json_encode(['lo']), 'timezone' => 'Asia/Vientiane', 'population' => 7276000, 'area_km2' => 236800.00, 'lat' => 19.8563, 'lng' => 102.4955, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'LB', 'iso3_code' => 'LBN', 'name_translations' => json_encode(['en' => 'Lebanon', 'de' => 'Libanon']), 'continent_id' => 2, 'is_eu_member' => false, 'currency_code' => 'LBP', 'currency_name' => 'Lebanese Pound', 'currency_symbol' => 'ل.ل', 'phone_prefix' => '+961', 'languages' => json_encode(['ar', 'fr']), 'timezone' => 'Asia/Beirut', 'population' => 6825000, 'area_km2' => 10400.00, 'lat' => 33.8547, 'lng' => 35.8623, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'LK', 'iso3_code' => 'LKA', 'name_translations' => json_encode(['en' => 'Sri Lanka', 'de' => 'Sri Lanka']), 'continent_id' => 2, 'is_eu_member' => false, 'currency_code' => 'LKR', 'currency_name' => 'Sri Lankan Rupee', 'currency_symbol' => 'Rs', 'phone_prefix' => '+94', 'languages' => json_encode(['si', 'ta']), 'timezone' => 'Asia/Colombo', 'population' => 21413000, 'area_km2' => 65610.00, 'lat' => 7.8731, 'lng' => 80.7718, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'MM', 'iso3_code' => 'MMR', 'name_translations' => json_encode(['en' => 'Myanmar', 'de' => 'Myanmar']), 'continent_id' => 2, 'is_eu_member' => false, 'currency_code' => 'MMK', 'currency_name' => 'Myanmar Kyat', 'currency_symbol' => 'K', 'phone_prefix' => '+95', 'languages' => json_encode(['my']), 'timezone' => 'Asia/Yangon', 'population' => 54410000, 'area_km2' => 676578.00, 'lat' => 21.9162, 'lng' => 95.9560, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'MN', 'iso3_code' => 'MNG', 'name_translations' => json_encode(['en' => 'Mongolia', 'de' => 'Mongolei']), 'continent_id' => 2, 'is_eu_member' => false, 'currency_code' => 'MNT', 'currency_name' => 'Mongolian Tugrik', 'currency_symbol' => '₮', 'phone_prefix' => '+976', 'languages' => json_encode(['mn']), 'timezone' => 'Asia/Ulaanbaatar', 'population' => 3278000, 'area_km2' => 1564110.00, 'lat' => 46.8625, 'lng' => 103.8467, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'MV', 'iso3_code' => 'MDV', 'name_translations' => json_encode(['en' => 'Maldives', 'de' => 'Malediven']), 'continent_id' => 2, 'is_eu_member' => false, 'currency_code' => 'MVR', 'currency_name' => 'Maldivian Rufiyaa', 'currency_symbol' => 'Rf', 'phone_prefix' => '+960', 'languages' => json_encode(['dv']), 'timezone' => 'Indian/Maldives', 'population' => 540000, 'area_km2' => 298.00, 'lat' => 3.2028, 'lng' => 73.2207, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'MY', 'iso3_code' => 'MYS', 'name_translations' => json_encode(['en' => 'Malaysia', 'de' => 'Malaysia']), 'continent_id' => 2, 'is_eu_member' => false, 'currency_code' => 'MYR', 'currency_name' => 'Malaysian Ringgit', 'currency_symbol' => 'RM', 'phone_prefix' => '+60', 'languages' => json_encode(['ms']), 'timezone' => 'Asia/Kuala_Lumpur', 'population' => 32366000, 'area_km2' => 329847.00, 'lat' => 4.2105, 'lng' => 101.9758, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'NP', 'iso3_code' => 'NPL', 'name_translations' => json_encode(['en' => 'Nepal', 'de' => 'Nepal']), 'continent_id' => 2, 'is_eu_member' => false, 'currency_code' => 'NPR', 'currency_name' => 'Nepalese Rupee', 'currency_symbol' => 'Rs', 'phone_prefix' => '+977', 'languages' => json_encode(['ne']), 'timezone' => 'Asia/Kathmandu', 'population' => 29137000, 'area_km2' => 147181.00, 'lat' => 28.3949, 'lng' => 84.1240, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'OM', 'iso3_code' => 'OMN', 'name_translations' => json_encode(['en' => 'Oman', 'de' => 'Oman']), 'continent_id' => 2, 'is_eu_member' => false, 'currency_code' => 'OMR', 'currency_name' => 'Omani Rial', 'currency_symbol' => 'ر.ع.', 'phone_prefix' => '+968', 'languages' => json_encode(['ar']), 'timezone' => 'Asia/Muscat', 'population' => 5107000, 'area_km2' => 309500.00, 'lat' => 21.4735, 'lng' => 55.9754, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'PH', 'iso3_code' => 'PHL', 'name_translations' => json_encode(['en' => 'Philippines', 'de' => 'Philippinen']), 'continent_id' => 2, 'is_eu_member' => false, 'currency_code' => 'PHP', 'currency_name' => 'Philippine Peso', 'currency_symbol' => '₱', 'phone_prefix' => '+63', 'languages' => json_encode(['en', 'tl']), 'timezone' => 'Asia/Manila', 'population' => 109581000, 'area_km2' => 300000.00, 'lat' => 12.8797, 'lng' => 121.7740, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'PK', 'iso3_code' => 'PAK', 'name_translations' => json_encode(['en' => 'Pakistan', 'de' => 'Pakistan']), 'continent_id' => 2, 'is_eu_member' => false, 'currency_code' => 'PKR', 'currency_name' => 'Pakistani Rupee', 'currency_symbol' => 'Rs', 'phone_prefix' => '+92', 'languages' => json_encode(['ur', 'en']), 'timezone' => 'Asia/Karachi', 'population' => 220892000, 'area_km2' => 796095.00, 'lat' => 30.3753, 'lng' => 69.3451, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'PS', 'iso3_code' => 'PSE', 'name_translations' => json_encode(['en' => 'Palestine', 'de' => 'Palästina']), 'continent_id' => 2, 'is_eu_member' => false, 'currency_code' => 'ILS', 'currency_name' => 'Israeli New Shekel', 'currency_symbol' => '₪', 'phone_prefix' => '+970', 'languages' => json_encode(['ar']), 'timezone' => 'Asia/Gaza', 'population' => 5101000, 'area_km2' => 6020.00, 'lat' => 31.9522, 'lng' => 35.2332, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'QA', 'iso3_code' => 'QAT', 'name_translations' => json_encode(['en' => 'Qatar', 'de' => 'Katar']), 'continent_id' => 2, 'is_eu_member' => false, 'currency_code' => 'QAR', 'currency_name' => 'Qatari Riyal', 'currency_symbol' => 'ر.ق', 'phone_prefix' => '+974', 'languages' => json_encode(['ar']), 'timezone' => 'Asia/Qatar', 'population' => 2881000, 'area_km2' => 11586.00, 'lat' => 25.3548, 'lng' => 51.1839, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'SA', 'iso3_code' => 'SAU', 'name_translations' => json_encode(['en' => 'Saudi Arabia', 'de' => 'Saudi-Arabien']), 'continent_id' => 2, 'is_eu_member' => false, 'currency_code' => 'SAR', 'currency_name' => 'Saudi Riyal', 'currency_symbol' => 'ر.س', 'phone_prefix' => '+966', 'languages' => json_encode(['ar']), 'timezone' => 'Asia/Riyadh', 'population' => 34814000, 'area_km2' => 2149690.00, 'lat' => 23.8859, 'lng' => 45.0792, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'SG', 'iso3_code' => 'SGP', 'name_translations' => json_encode(['en' => 'Singapore', 'de' => 'Singapur']), 'continent_id' => 2, 'is_eu_member' => false, 'currency_code' => 'SGD', 'currency_name' => 'Singapore Dollar', 'currency_symbol' => 'S$', 'phone_prefix' => '+65', 'languages' => json_encode(['en', 'ms', 'ta', 'zh']), 'timezone' => 'Asia/Singapore', 'population' => 5850000, 'area_km2' => 719.00, 'lat' => 1.3521, 'lng' => 103.8198, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'SY', 'iso3_code' => 'SYR', 'name_translations' => json_encode(['en' => 'Syria', 'de' => 'Syrien']), 'continent_id' => 2, 'is_eu_member' => false, 'currency_code' => 'SYP', 'currency_name' => 'Syrian Pound', 'currency_symbol' => 'ل.س', 'phone_prefix' => '+963', 'languages' => json_encode(['ar']), 'timezone' => 'Asia/Damascus', 'population' => 17501000, 'area_km2' => 185180.00, 'lat' => 34.8021, 'lng' => 38.9968, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'TH', 'iso3_code' => 'THA', 'name_translations' => json_encode(['en' => 'Thailand', 'de' => 'Thailand']), 'continent_id' => 2, 'is_eu_member' => false, 'currency_code' => 'THB', 'currency_name' => 'Thai Baht', 'currency_symbol' => '฿', 'phone_prefix' => '+66', 'languages' => json_encode(['th']), 'timezone' => 'Asia/Bangkok', 'population' => 69800000, 'area_km2' => 513120.00, 'lat' => 15.8700, 'lng' => 100.9925, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'TJ', 'iso3_code' => 'TJK', 'name_translations' => json_encode(['en' => 'Tajikistan', 'de' => 'Tadschikistan']), 'continent_id' => 2, 'is_eu_member' => false, 'currency_code' => 'TJS', 'currency_name' => 'Tajikistani Somoni', 'currency_symbol' => 'ЅМ', 'phone_prefix' => '+992', 'languages' => json_encode(['tg', 'ru']), 'timezone' => 'Asia/Dushanbe', 'population' => 9538000, 'area_km2' => 143100.00, 'lat' => 38.8610, 'lng' => 71.2761, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'TL', 'iso3_code' => 'TLS', 'name_translations' => json_encode(['en' => 'East Timor', 'de' => 'Osttimor']), 'continent_id' => 2, 'is_eu_member' => false, 'currency_code' => 'USD', 'currency_name' => 'United States Dollar', 'currency_symbol' => '$', 'phone_prefix' => '+670', 'languages' => json_encode(['pt', 'tet']), 'timezone' => 'Asia/Dili', 'population' => 1318000, 'area_km2' => 14874.00, 'lat' => -8.8742, 'lng' => 125.7275, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'TM', 'iso3_code' => 'TKM', 'name_translations' => json_encode(['en' => 'Turkmenistan', 'de' => 'Turkmenistan']), 'continent_id' => 2, 'is_eu_member' => false, 'currency_code' => 'TMT', 'currency_name' => 'Turkmenistani Manat', 'currency_symbol' => 'm', 'phone_prefix' => '+993', 'languages' => json_encode(['tk']), 'timezone' => 'Asia/Ashgabat', 'population' => 6031000, 'area_km2' => 488100.00, 'lat' => 38.9697, 'lng' => 59.5563, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'TR', 'iso3_code' => 'TUR', 'name_translations' => json_encode(['en' => 'Turkey', 'de' => 'Türkei']), 'continent_id' => 2, 'is_eu_member' => false, 'currency_code' => 'TRY', 'currency_name' => 'Turkish Lira', 'currency_symbol' => '₺', 'phone_prefix' => '+90', 'languages' => json_encode(['tr']), 'timezone' => 'Europe/Istanbul', 'population' => 84339000, 'area_km2' => 783562.00, 'lat' => 38.9637, 'lng' => 35.2433, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'TW', 'iso3_code' => 'TWN', 'name_translations' => json_encode(['en' => 'Taiwan', 'de' => 'Taiwan']), 'continent_id' => 2, 'is_eu_member' => false, 'currency_code' => 'TWD', 'currency_name' => 'New Taiwan Dollar', 'currency_symbol' => 'NT$', 'phone_prefix' => '+886', 'languages' => json_encode(['zh']), 'timezone' => 'Asia/Taipei', 'population' => 23816000, 'area_km2' => 36193.00, 'lat' => 23.6978, 'lng' => 120.9605, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'UZ', 'iso3_code' => 'UZB', 'name_translations' => json_encode(['en' => 'Uzbekistan', 'de' => 'Usbekistan']), 'continent_id' => 2, 'is_eu_member' => false, 'currency_code' => 'UZS', 'currency_name' => 'Uzbekistan Som', 'currency_symbol' => 'лв', 'phone_prefix' => '+998', 'languages' => json_encode(['uz', 'ru']), 'timezone' => 'Asia/Tashkent', 'population' => 33469000, 'area_km2' => 447400.00, 'lat' => 41.3775, 'lng' => 64.5853, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'VN', 'iso3_code' => 'VNM', 'name_translations' => json_encode(['en' => 'Vietnam', 'de' => 'Vietnam']), 'continent_id' => 2, 'is_eu_member' => false, 'currency_code' => 'VND', 'currency_name' => 'Vietnamese Dong', 'currency_symbol' => '₫', 'phone_prefix' => '+84', 'languages' => json_encode(['vi']), 'timezone' => 'Asia/Ho_Chi_Minh', 'population' => 97339000, 'area_km2' => 331212.00, 'lat' => 14.0583, 'lng' => 108.2772, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'YE', 'iso3_code' => 'YEM', 'name_translations' => json_encode(['en' => 'Yemen', 'de' => 'Jemen']), 'continent_id' => 2, 'is_eu_member' => false, 'currency_code' => 'YER', 'currency_name' => 'Yemeni Rial', 'currency_symbol' => '﷼', 'phone_prefix' => '+967', 'languages' => json_encode(['ar']), 'timezone' => 'Asia/Aden', 'population' => 29826000, 'area_km2' => 527968.00, 'lat' => 15.5527, 'lng' => 48.5164, 'created_at' => now(), 'updated_at' => now()],

            // Afrika (continent_id: 3) - Auswahl wichtiger Länder
            ['iso_code' => 'DZ', 'iso3_code' => 'DZA', 'name_translations' => json_encode(['en' => 'Algeria', 'de' => 'Algerien']), 'continent_id' => 3, 'is_eu_member' => false, 'currency_code' => 'DZD', 'currency_name' => 'Algerian Dinar', 'currency_symbol' => 'د.ج', 'phone_prefix' => '+213', 'languages' => json_encode(['ar', 'fr']), 'timezone' => 'Africa/Algiers', 'population' => 43851000, 'area_km2' => 2381741.00, 'lat' => 28.0339, 'lng' => 1.6596, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'EG', 'iso3_code' => 'EGY', 'name_translations' => json_encode(['en' => 'Egypt', 'de' => 'Ägypten']), 'continent_id' => 3, 'is_eu_member' => false, 'currency_code' => 'EGP', 'currency_name' => 'Egyptian Pound', 'currency_symbol' => '£', 'phone_prefix' => '+20', 'languages' => json_encode(['ar']), 'timezone' => 'Africa/Cairo', 'population' => 102334000, 'area_km2' => 1001449.00, 'lat' => 26.8206, 'lng' => 30.8025, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'MA', 'iso3_code' => 'MAR', 'name_translations' => json_encode(['en' => 'Morocco', 'de' => 'Marokko']), 'continent_id' => 3, 'is_eu_member' => false, 'currency_code' => 'MAD', 'currency_name' => 'Moroccan Dirham', 'currency_symbol' => 'د.م.', 'phone_prefix' => '+212', 'languages' => json_encode(['ar', 'fr']), 'timezone' => 'Africa/Casablanca', 'population' => 36911000, 'area_km2' => 446550.00, 'lat' => 31.7917, 'lng' => -7.0926, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'NG', 'iso3_code' => 'NGA', 'name_translations' => json_encode(['en' => 'Nigeria', 'de' => 'Nigeria']), 'continent_id' => 3, 'is_eu_member' => false, 'currency_code' => 'NGN', 'currency_name' => 'Nigerian Naira', 'currency_symbol' => '₦', 'phone_prefix' => '+234', 'languages' => json_encode(['en']), 'timezone' => 'Africa/Lagos', 'population' => 206140000, 'area_km2' => 923768.00, 'lat' => 9.0820, 'lng' => 8.6753, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'ZA', 'iso3_code' => 'ZAF', 'name_translations' => json_encode(['en' => 'South Africa', 'de' => 'Südafrika']), 'continent_id' => 3, 'is_eu_member' => false, 'currency_code' => 'ZAR', 'currency_name' => 'South African Rand', 'currency_symbol' => 'R', 'phone_prefix' => '+27', 'languages' => json_encode(['af', 'en', 'zu', 'xh']), 'timezone' => 'Africa/Johannesburg', 'population' => 59309000, 'area_km2' => 1221037.00, 'lat' => -30.5595, 'lng' => 22.9375, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'KE', 'iso3_code' => 'KEN', 'name_translations' => json_encode(['en' => 'Kenya', 'de' => 'Kenia']), 'continent_id' => 3, 'is_eu_member' => false, 'currency_code' => 'KES', 'currency_name' => 'Kenyan Shilling', 'currency_symbol' => 'KSh', 'phone_prefix' => '+254', 'languages' => json_encode(['en', 'sw']), 'timezone' => 'Africa/Nairobi', 'population' => 53771000, 'area_km2' => 580367.00, 'lat' => -0.0236, 'lng' => 37.9062, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'GH', 'iso3_code' => 'GHA', 'name_translations' => json_encode(['en' => 'Ghana', 'de' => 'Ghana']), 'continent_id' => 3, 'is_eu_member' => false, 'currency_code' => 'GHS', 'currency_name' => 'Ghanaian Cedi', 'currency_symbol' => '₵', 'phone_prefix' => '+233', 'languages' => json_encode(['en']), 'timezone' => 'Africa/Accra', 'population' => 31073000, 'area_km2' => 238533.00, 'lat' => 7.9465, 'lng' => -1.0232, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'ET', 'iso3_code' => 'ETH', 'name_translations' => json_encode(['en' => 'Ethiopia', 'de' => 'Äthiopien']), 'continent_id' => 3, 'is_eu_member' => false, 'currency_code' => 'ETB', 'currency_name' => 'Ethiopian Birr', 'currency_symbol' => 'Br', 'phone_prefix' => '+251', 'languages' => json_encode(['am']), 'timezone' => 'Africa/Addis_Ababa', 'population' => 115000000, 'area_km2' => 1104300.00, 'lat' => 9.1450, 'lng' => 40.4897, 'created_at' => now(), 'updated_at' => now()],

            // Nordamerika (continent_id: 4)
            ['iso_code' => 'CA', 'iso3_code' => 'CAN', 'name_translations' => json_encode(['en' => 'Canada', 'de' => 'Kanada']), 'continent_id' => 4, 'is_eu_member' => false, 'currency_code' => 'CAD', 'currency_name' => 'Canadian Dollar', 'currency_symbol' => '$', 'phone_prefix' => '+1', 'languages' => json_encode(['en', 'fr']), 'timezone' => 'America/Toronto', 'population' => 37742000, 'area_km2' => 9984670.00, 'lat' => 56.1304, 'lng' => -106.3468, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'US', 'iso3_code' => 'USA', 'name_translations' => json_encode(['en' => 'United States', 'de' => 'Vereinigte Staaten']), 'continent_id' => 4, 'is_eu_member' => false, 'currency_code' => 'USD', 'currency_name' => 'United States Dollar', 'currency_symbol' => '$', 'phone_prefix' => '+1', 'languages' => json_encode(['en']), 'timezone' => 'America/New_York', 'population' => 331003000, 'area_km2' => 9833517.00, 'lat' => 37.0902, 'lng' => -95.7129, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'MX', 'iso3_code' => 'MEX', 'name_translations' => json_encode(['en' => 'Mexico', 'de' => 'Mexiko']), 'continent_id' => 4, 'is_eu_member' => false, 'currency_code' => 'MXN', 'currency_name' => 'Mexican Peso', 'currency_symbol' => '$', 'phone_prefix' => '+52', 'languages' => json_encode(['es']), 'timezone' => 'America/Mexico_City', 'population' => 128933000, 'area_km2' => 1964375.00, 'lat' => 23.6345, 'lng' => -102.5528, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'GT', 'iso3_code' => 'GTM', 'name_translations' => json_encode(['en' => 'Guatemala', 'de' => 'Guatemala']), 'continent_id' => 4, 'is_eu_member' => false, 'currency_code' => 'GTQ', 'currency_name' => 'Guatemalan Quetzal', 'currency_symbol' => 'Q', 'phone_prefix' => '+502', 'languages' => json_encode(['es']), 'timezone' => 'America/Guatemala', 'population' => 17916000, 'area_km2' => 108889.00, 'lat' => 15.7835, 'lng' => -90.2308, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'CR', 'iso3_code' => 'CRI', 'name_translations' => json_encode(['en' => 'Costa Rica', 'de' => 'Costa Rica']), 'continent_id' => 4, 'is_eu_member' => false, 'currency_code' => 'CRC', 'currency_name' => 'Costa Rican Colón', 'currency_symbol' => '₡', 'phone_prefix' => '+506', 'languages' => json_encode(['es']), 'timezone' => 'America/Costa_Rica', 'population' => 5094000, 'area_km2' => 51100.00, 'lat' => 9.7489, 'lng' => -83.7534, 'created_at' => now(), 'updated_at' => now()],

            // Südamerika (continent_id: 5)
            ['iso_code' => 'AR', 'iso3_code' => 'ARG', 'name_translations' => json_encode(['en' => 'Argentina', 'de' => 'Argentinien']), 'continent_id' => 5, 'is_eu_member' => false, 'currency_code' => 'ARS', 'currency_name' => 'Argentine Peso', 'currency_symbol' => '$', 'phone_prefix' => '+54', 'languages' => json_encode(['es']), 'timezone' => 'America/Argentina/Buenos_Aires', 'population' => 45196000, 'area_km2' => 2780400.00, 'lat' => -38.4161, 'lng' => -63.6167, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'BR', 'iso3_code' => 'BRA', 'name_translations' => json_encode(['en' => 'Brazil', 'de' => 'Brasilien']), 'continent_id' => 5, 'is_eu_member' => false, 'currency_code' => 'BRL', 'currency_name' => 'Brazilian Real', 'currency_symbol' => 'R$', 'phone_prefix' => '+55', 'languages' => json_encode(['pt']), 'timezone' => 'America/Sao_Paulo', 'population' => 212559000, 'area_km2' => 8514877.00, 'lat' => -14.2350, 'lng' => -51.9253, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'CL', 'iso3_code' => 'CHL', 'name_translations' => json_encode(['en' => 'Chile', 'de' => 'Chile']), 'continent_id' => 5, 'is_eu_member' => false, 'currency_code' => 'CLP', 'currency_name' => 'Chilean Peso', 'currency_symbol' => '$', 'phone_prefix' => '+56', 'languages' => json_encode(['es']), 'timezone' => 'America/Santiago', 'population' => 19116000, 'area_km2' => 756096.00, 'lat' => -35.6751, 'lng' => -71.5430, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'CO', 'iso3_code' => 'COL', 'name_translations' => json_encode(['en' => 'Colombia', 'de' => 'Kolumbien']), 'continent_id' => 5, 'is_eu_member' => false, 'currency_code' => 'COP', 'currency_name' => 'Colombian Peso', 'currency_symbol' => '$', 'phone_prefix' => '+57', 'languages' => json_encode(['es']), 'timezone' => 'America/Bogota', 'population' => 50883000, 'area_km2' => 1141748.00, 'lat' => 4.5709, 'lng' => -74.2973, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'PE', 'iso3_code' => 'PER', 'name_translations' => json_encode(['en' => 'Peru', 'de' => 'Peru']), 'continent_id' => 5, 'is_eu_member' => false, 'currency_code' => 'PEN', 'currency_name' => 'Peruvian Sol', 'currency_symbol' => 'S/', 'phone_prefix' => '+51', 'languages' => json_encode(['es', 'qu']), 'timezone' => 'America/Lima', 'population' => 32972000, 'area_km2' => 1285216.00, 'lat' => -9.1900, 'lng' => -75.0152, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'VE', 'iso3_code' => 'VEN', 'name_translations' => json_encode(['en' => 'Venezuela', 'de' => 'Venezuela']), 'continent_id' => 5, 'is_eu_member' => false, 'currency_code' => 'VES', 'currency_name' => 'Venezuelan Bolívar Soberano', 'currency_symbol' => 'Bs.S', 'phone_prefix' => '+58', 'languages' => json_encode(['es']), 'timezone' => 'America/Caracas', 'population' => 28436000, 'area_km2' => 912050.00, 'lat' => 6.4238, 'lng' => -66.5897, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'EC', 'iso3_code' => 'ECU', 'name_translations' => json_encode(['en' => 'Ecuador', 'de' => 'Ecuador']), 'continent_id' => 5, 'is_eu_member' => false, 'currency_code' => 'USD', 'currency_name' => 'United States Dollar', 'currency_symbol' => '$', 'phone_prefix' => '+593', 'languages' => json_encode(['es']), 'timezone' => 'America/Guayaquil', 'population' => 17644000, 'area_km2' => 283561.00, 'lat' => -1.8312, 'lng' => -78.1834, 'created_at' => now(), 'updated_at' => now()],

            // Australien/Ozeanien (continent_id: 6)
            ['iso_code' => 'AU', 'iso3_code' => 'AUS', 'name_translations' => json_encode(['en' => 'Australia', 'de' => 'Australien']), 'continent_id' => 6, 'is_eu_member' => false, 'currency_code' => 'AUD', 'currency_name' => 'Australian Dollar', 'currency_symbol' => '$', 'phone_prefix' => '+61', 'languages' => json_encode(['en']), 'timezone' => 'Australia/Sydney', 'population' => 25500000, 'area_km2' => 7692024.00, 'lat' => -25.2744, 'lng' => 133.7751, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'NZ', 'iso3_code' => 'NZL', 'name_translations' => json_encode(['en' => 'New Zealand', 'de' => 'Neuseeland']), 'continent_id' => 6, 'is_eu_member' => false, 'currency_code' => 'NZD', 'currency_name' => 'New Zealand Dollar', 'currency_symbol' => '$', 'phone_prefix' => '+64', 'languages' => json_encode(['en', 'mi']), 'timezone' => 'Pacific/Auckland', 'population' => 4822000, 'area_km2' => 268838.00, 'lat' => -40.9006, 'lng' => 174.8860, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'FJ', 'iso3_code' => 'FJI', 'name_translations' => json_encode(['en' => 'Fiji', 'de' => 'Fidschi']), 'continent_id' => 6, 'is_eu_member' => false, 'currency_code' => 'FJD', 'currency_name' => 'Fijian Dollar', 'currency_symbol' => '$', 'phone_prefix' => '+679', 'languages' => json_encode(['en', 'fj']), 'timezone' => 'Pacific/Fiji', 'population' => 896000, 'area_km2' => 18274.00, 'lat' => -16.7784, 'lng' => 179.4144, 'created_at' => now(), 'updated_at' => now()],
            ['iso_code' => 'PG', 'iso3_code' => 'PNG', 'name_translations' => json_encode(['en' => 'Papua New Guinea', 'de' => 'Papua-Neuguinea']), 'continent_id' => 6, 'is_eu_member' => false, 'currency_code' => 'PGK', 'currency_name' => 'Papua New Guinean Kina', 'currency_symbol' => 'K', 'phone_prefix' => '+675', 'languages' => json_encode(['en']), 'timezone' => 'Pacific/Port_Moresby', 'population' => 8947000, 'area_km2' => 462840.00, 'lat' => -6.3140, 'lng' => 143.9555, 'created_at' => now(), 'updated_at' => now()],
        ];
    }
}